backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "berita"
    label: "Berita & Kegiatan"
    folder: "_data/berita"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul Acara / Kegiatan", name: "title", widget: "string" }
      - { label: "Tanggal Acara", name: "date", widget: "date", format: "YYYY-MM-DD" }
      - { label: "Foto Utama Dokumentasi", name: "image", widget: "image" }
      - { label: "Foto Tambahan (Bisa Banyak)", name: "gallery", widget: "list", summary: "{{fields.img}}", field: { label: "Unggah Foto", name: "img", widget: "image" } }
      - { label: "Isi Lengkap Berita / Artikel", name: "body", widget: "markdown" }

  - name: "program"
    label: "Program Kerja"
    folder: "_data/program"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama Program", name: "title", widget: "string" }
      - { label: "Kategori", name: "kategori", widget: "select", options: ["Sosial", "Olahraga", "Keagamaan"] }
      - { label: "Deskripsi Singkat", name: "deskripsi", widget: "text" }
      - { label: "Tag/Slogan", name: "tag", widget: "string", placeholder: "Contoh: Kekeluargaan, Sportivitas" }

  - name: "settings"
    label: "Pengaturan Website"
    delete: false
    editor:
      preview: false
    files:
      - name: "appearance"
        label: "Konten & Banner Utama"
        file: "_data/settings.json"
        fields:
          - { label: "Foto Wallpaper Atas", name: "hero_image", widget: "image" }
          - { label: "Kalimat Deskripsi Utama", name: "deskripsi_utama", widget: "text" }
          - { label: "Teks Visi", name: "visi_teks", widget: "text" }
          - { label: "Teks Misi", name: "misi_teks", widget: "text" }
          - { label: "Email Resmi Organisasi", name: "email_kontak", widget: "string" }
