backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "berita"
    label: "Berita & Kegiatan"
    folder: "_data/berita"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul Acara / Kegiatan", name: "title", widget: "string" }
      - { label: "Tanggal Acara", name: "date", widget: "date", format: "YYYY-MM-DD" }
      - { label: "Foto Utama Dokumentasi", name: "image", widget: "image", required: false }
      - { label: "Foto Tambahan (Bisa Banyak)", name: "gallery", widget: "list", required: false, summary: "{{fields.img}}", field: { label: "Unggah Foto", name: "img", widget: "image" } }
      - { label: "Isi Lengkap Berita / Artikel (Bisa Dikosongkan)", name: "body", widget: "markdown", required: false }

  - name: "program"
    label: "Program Kerja"
    folder: "_data/program"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama Program", name: "title", widget: "string" }
      - { label: "Kategori", name: "kategori", widget: "select", options: ["Sosial", "Olahraga", "Keagamaan"] }
      - { label: "Deskripsi Singkat", name: "deskripsi", widget: "text" }
      - { label: "Tag/Slogan", name: "tag", widget: "string", placeholder: "Contoh: Kekeluargaan, Sportivitas" }

  - name: "settings"
    label: "Pengaturan Website"
    delete: false
    editor:
      preview: false
    files:
      - name: "banner"
        label: "1. Banner & Kontak Atas"
        file: "_data/banner.json"
        fields:
          - { label: "Foto Wallpaper Paling Atas", name: "hero_image", widget: "image", required: false }
          - { label: "Kalimat Deskripsi Utama Atas", name: "deskripsi_utama", widget: "text", required: false }
          - { label: "Email Resmi Organisasi", name: "email_kontak", widget: "string", required: false }

      - name: "visimisi"
        label: "2. Visi & Misi"
        file: "_data/visimisi.json"
        fields:
          - { label: "Teks Visi", name: "visi_teks", widget: "text", required: false }
          - { label: "Teks Misi", name: "misi_teks", widget: "text", required: false }

      - name: "tentang"
        label: "3. Profil Tentang Kami"
        file: "_data/tentang.json"
        fields:
          - { label: "Foto/Gambar Tentang Kami", name: "tentang_image", widget: "image", required: false }
          - { label: "Judul Tentang Kami", name: "tentang_judul", widget: "string", required: false }
          - { label: "Penjelasan Tentang Kami (Paragraf 1)", name: "tentang_p1", widget: "text", required: false }
          - { label: "Penjelasan Tentang Kami (Paragraf 2)", name: "tentang_p2", widget: "text", required: false }
